In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

Pytorch is an open source python deep learning library. It's one the most widely used deep learning library for research since 2019. It is popular because of it's user friendly interface and efficiency. It is accessible, flexibled and allows adavanced users to tweak lower level aspects of their models for customization and optimization.

Core components of PyTorch - 

1. Tensor Library - PyTorch library implements a tensor array for efficient computing
2. Automatic Differentiation Engine - PyTorch includes utilities to differentiate computations automatically.
3. Deep learning library. - Deep learning utilities that use of above two

So Tensors are the fundamental building blocks for computing, the automatic differentiation engine for model optimization, and deep learning utility functions to implement and train deep neural network models.

Let's now look at Tensors in detail.

Tensors are similar to NumPy's ndarrays, except that tensors can run on GPU's and other hardware accelerators. It extends the concepts of array-oriented programming library NumPy with the additional feature of accelerated computation offering seamless switch between CPU and GPU. Tensors and NumPy arrays can often share the same underlying memory, eliminating copy data. Tensors are also optimized for Automatic Differentiation which we will explore later. Tensors are mainly used to encode inputs and outputs of a model, as well as the model'parameters. 

Let's go ahead to explore about Tensor's - 

In [2]:
import torch
import numpy as np

In [3]:
# Intializing a Tensor - Using data directly

data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
# Intializing a Tensor - Using NumPy Array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
# Intializing a Tensor - Using another tensor

x_ones = torch.ones_like(x_data) # Retains the properties of x_data like the size being 2 x 2

print(f'Ones Tensor: \n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f'Random Tensor: \n {x_rand} \n')


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9958, 0.7344],
        [0.2672, 0.9389]]) 

